#version: "3"

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.6"
    ports:
      - 9200:9200
    restart: on-failure
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    healthcheck:
        test: curl --fail http://localhost:9200/_cat/health || exit 1
        interval: 10s
        timeout: 1s
        retries: 10

  haystack-api:
    image: "deepset/haystack:cpu-v1.12.0"
    volumes:
      - ./:/opt/pipelines
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      - DOCUMENTSTORE_PARAMS_HOST=elasticsearch
      - PIPELINE_YAML_PATH=/opt/pipelines/document-search.haystack-pipeline.yml
    depends_on:
      elasticsearch:
        condition: service_healthy

#  ui:
#    image: "deepset/demo-explore-the-world"
#    ports:
#     - 8501:8501
#   restart: on-failure
#   environment:
#     - API_ENDPOINT=http://haystack-api:8000
      # The value fot the following variables will be read from the host, if present.
      # They can also be temporarily set for docker-compose, for example:
      # $ DISABLE_FILE_UPLOAD=1 DEFAULT_DOCS_FROM_RETRIEVER=5 docker-compose up
#     - DISABLE_FILE_UPLOAD
#     - DEFAULT_QUESTION_AT_STARTUP
#     - DEFAULT_DOCS_FROM_RETRIEVER
#     - DEFAULT_NUMBER_OF_ANSWERS
#   command: "/bin/bash -c 'sleep 15 && python -m streamlit run ui/webapp.py'"
